add author avatar and name
zer0-os/zOS pull request #155
Opened 2022-09-01 12:33 UTC by mrval5

### What does this do?
add author avatar and name.

<img width="1285" alt="Screenshot 2022-09-01 at 14 30 46" src="https://user-images.githubusercontent.com/102802882/187914174-391ffe2b-d148-450a-9ccb-7fa5a9f37673.png">

2022-09-01 13:29 UTC, hkhanouchi approved these changes

2022-09-01 13:44 UTC, jtulloch requested changes
just the one thing.

2022-09-01 13:44 UTC, jtulloch commented on src/platform-apps/channels/styles.scss
> +      color: #cccccc;
let's use a theme variable for this.

2022-09-06 13:39 UTC, jtulloch requested changes

2022-09-07 14:15 UTC, jtulloch approved these changes

2022-09-07 14:31 UTC, merged