Add reply message to channel
zer0-os/zOS pull request #336
Opened 2023-01-26 12:36 UTC by hkhanouchi

https://user-images.githubusercontent.com/27851097/214836893-2b152547-f4db-413a-9249-0bd880f44604.mov

2023-01-26 16:05 UTC, mrval5 requested changes

2023-01-26 16:05 UTC, mrval5 commented on src/components/message-input/styles.scss
> +    color: var(--accent-color);
also theme, and the border below

2023-01-26 16:05 UTC, mrval5 commented on src/components/message-input/reply-card.tsx
> +import { IconButton, Icons } from '@zer0-os/zos-component-library';
maybe better to make a new folder for `replay-card`

2023-01-26 16:05 UTC, mrval5 commented on src/components/message-input/reply-card.test.tsx
> +describe('ReplyCardReplyCard', () => {
```suggestion
describe('ReplyCard', () => {
```

2023-01-27 14:36 UTC, mrval5 approved these changes

2023-01-27 15:25 UTC, merged

2023-01-30 16:16 UTC, dalefukami commented on src/platform-apps/channels/messages-menu/index.tsx
> +        {this.showDeleteModal && this.renderDeleteModal()}
This is suspicious to me. Rendering the delete modal twice?