Add recording voice message
zer0-os/zOS pull request #386
Opened 2023-03-01 19:10 UTC by hkhanouchi

https://user-images.githubusercontent.com/27851097/222240238-a30e6595-2ff2-427a-bba2-7eceefd6ca0a.mov

2023-03-02 03:27 UTC, AdamDotCom commented
@hkhanouchi, it looks like the `uploadFileMessage` function should also work for uploading audio files: https://github.com/zer0-os/zOS/blob/main/src/store/messages/api.ts#L54

2023-03-02 10:46 UTC, hkhanouchi commented
> @hkhanouchi, it looks like the `uploadFileMessage` function should also work for uploading audio files: https://github.com/zer0-os/zOS/blob/main/src/store/messages/api.ts#L54 What happens when you send the audio file to that endpoint?

@AdamDotCom yes, that's what I thought too, but it gives me this error. 

![Screen Shot 2023-03-01 at 14 39 37](https://user-images.githubusercontent.com/27851097/222406889-56882500-8091-4a55-90b5-92456a5f0adb.png)

2023-03-03 12:22 UTC, hkhanouchi commented
i have a Conflicting peer dependency `peer react@"16.x" from react-mic@12.4.6`, I tried overriding the dependency but it still doesn't work. if you have any idea i am listening.

2023-03-03 20:12 UTC, AdamDotCom requested changes

2023-03-03 20:12 UTC, AdamDotCom commented on src/components/message-input/index.test.tsx
> +    (wrapper.instance() as any).startMic();
```suggestion
    wrapper.find('.record-voice__icon').simulate('click')
```
In most of our other tests we're avoiding calling instance. Can we simulate the user event for click?

2023-03-03 20:12 UTC, AdamDotCom commented on src/components/message-input/index.test.tsx
> +    const dropzone2 = wrapper.find(Dropzone).shallow();
Are we able to reuse the `dropzone` reference from above? I think `dropzone.update()` or `dropzone.setProps({})` should trigger a re-render.

2023-03-03 20:15 UTC, AdamDotCom commented on package.json
> +  "version": "0.10.1",
```suggestion
  "version": "0.10.0",
```
We shouldn't need to increase the version number unless we want to trigger a Production release.

2023-03-04 03:37 UTC, AdamDotCom commented
@hkhanouchi, how hard would it be to use a more modern audio recording component? If we moved to https://github.com/samhirtarif/react-audio-recorder or something more modern?

2023-03-06 16:53 UTC, merged