zOS: Link Preview is disappearing
zer0-os/zOS pull request #392
Opened 2023-03-14 12:31 UTC by ratik21

### What does this do?

Fixes the link disappearing issue.

### Why are we making this change?

Link preview was disappearing "immediately" after sending a message with a link preview. 

### How do I test this?

Try sending a message with link preview in zOS. It should not disappear now.

2023-03-14 13:48 UTC, hkhanouchi approved these changes

2023-03-14 14:50 UTC, AdamDotCom requested changes
Nice! I can't believe it was that straight forward. Could we add a saga test too to make sure we don't remove this preview logic in the future? We should have some examples in src/store/messages/saga.test.ts. There's also some guidance at https://redux-saga.js.org/docs/advanced/Testing/#redux-saga-test-plan

2023-03-15 06:29 UTC, ratik21 commented
@AdamDotCom added

2023-03-15 14:44 UTC, AdamDotCom approved these changes

2023-03-15 18:32 UTC, merged