Ability to remove link preview from message
zer0-os/zOS pull request #405
Opened 2023-03-16 13:10 UTC by ratik21

<img width="552" alt="image" src="https://user-images.githubusercontent.com/33264364/225626763-68cd5f23-da35-4564-98c8-3e7a1d9bb578.png">

After removing:

<img width="560" alt="image" src="https://user-images.githubusercontent.com/33264364/225626832-a6c582ff-8c84-42c1-a313-51e34104d702.png">

2023-03-16 16:56 UTC, hkhanouchi commented on src/components/message/index.tsx
> +                  {preview && hidePreview === false && (
`{preview && !hidePreview && (`

2023-03-20 09:23 UTC, mrval5 requested changes

2023-03-20 09:23 UTC, mrval5 commented on src/store/messages/api.ts
> +  data?: object
what is data ? what is the structure of it that we are using in zOS ?

2023-03-20 09:23 UTC, mrval5 commented on src/store/messages/saga.ts
> +      return { ...selectedMessage, updatedAt: Date.now(), message, hidePreview: data?.hidePreview ?? false };
Maybe:
```suggestion
      return { ...selectedMessage, updatedAt: Date.now(), message, hidePreview: Boolean(data?.hidePreview)};
```

2023-03-20 09:23 UTC, mrval5 commented on src/store/messages/api.ts
> +  data?: object
I understood it's like optional `options` which it contains `hidePreview`, le's add the type please

2023-03-20 15:34 UTC, mrval5 approved these changes

2023-03-20 20:46 UTC, merged