Add link to logo
zer0-os/zOS pull request #72
Opened 2022-06-09 17:04 UTC by hkhanouchi

### What does this do?

### Why are we making this change?

### How do I test this?

### Key decisions and Risk Assessment:
  #### Things to consider:
  1. How will this affect security?
  1. How will this affect performance?
  1. Does this change any APIs?

2022-06-13 13:16 UTC, jtulloch requested changes

2022-06-13 13:16 UTC, jtulloch commented on src/components/logo/index.test.tsx
> +  it('adds className', () => {
looks good, but let's add a test to make sure the link is getting the right `to`, please. :)

2022-06-13 18:27 UTC, AdamDotCom approved these changes

2022-06-14 17:27 UTC, jtulloch approved these changes

2022-06-14 21:41 UTC, merged