Responsive grid using tailwind
zer0-os/zOS pull request #8
Opened 2022-02-22 19:43 UTC by AdamDotCom

"Tailwind CSS works by scanning all of your HTML files, JavaScript components, and any other templates for class names, generating the corresponding styles and then writing them to a static CSS file.

It's fast, flexible, and reliable — with zero-runtime." https://tailwindcss.com/docs/installation

2022-02-23 17:34 UTC, jtulloch requested changes
so, general thought is that this seems fine, but we should keep it isolated to layout. since markup and layout styles always directly correspond, i think it makes sense to have those things together.

2022-02-25 19:24 UTC, AdamDotCom commented on src/index.tsx
> +      <div className='basis-[3.5rem]'>{/* World navigation */}</div>
It is possible to assign a class of say `world-navigation` to `basis-[xyz]` if numbers are visual clutter. CSS variables can also be used to set the numeric values if we want the values to be defined somewhere else altogether.
 
Tailwind has media query capabilities through class prefixes defined similar to `md:world-navigation`, this allows expand / collapse, buttons customization etc... if you wanted to use Tailwind outside of layout markup.

2022-02-25 19:26 UTC, AdamDotCom commented on src/Main.tsx
> +            <span className='text-3xl'>zOS</span>
“i don’t think we want to give up the benefits of the C part of CSS” Sounds like you need to get yourself on a pulpit! Preach it! :)

`text-3xl` shouldn't have been there. It was a fragment from getting tailwind configured.

2022-02-25 19:39 UTC, AdamDotCom commented on src/Main.tsx
> +            <span className='text-3xl'>zOS</span>
I'm not sure where we'd lose the Cascade though, font could be cascading from the parent. If you wanted to apply a unique font the Tailwind way you'd likely have `text-3xl font-sans`. 

`text-3xl` corresponds to:
```
.text-3xl {
  font-size: 1.875rem;
  line-height: 2.25rem;
}
```

2022-02-28 18:24 UTC, closed without merging