fix: remove outdated fix scroll behaviours
zer0-os/zOS pull request #956
Opened 2023-08-25 06:24 UTC by domw30

### What does this do?
- Removes the outdated fixScroll function from the InvertedScroll component.
- Simplifies the scrolling logic, leading to more predictable behaviour.

### Why are we making this change?
- To resolve the unexpected "scroll to bottom" behavior seen when editing messages or loading older messages.
- To improve the performance of the InvertedScroll component by eliminating redundant and excessive function calls.
- To make the component more maintainable by reducing complexity.

### How do I test this?
- Open messenger and when a conversation has loaded, immediately attempt to edit a message, or scroll up to load older messages. The scroll to bottom should no longer occur.

### Key decisions and Risk Assessment:
  #### Things to consider:
  1. How will this affect security?
  1. How will this affect performance?
  1. Does this change any APIs?

Whats happening - 

https://github.com/zer0-os/zOS/assets/39112648/c3c6fd10-9691-4ce5-8f4f-d11af388e2e3

While investigating, especially when editing or triggering the load of older messages, I identified that the root cause was tied to the fixScroll function in our InvertedScroll component (code that was added 9 months ago). This function was continuously being called up to a 1000 times (for roughly 5-10 seconds) after a particular event, such as a new element containing InvertedScroll was initialised.

This frequent and redundant execution appears to be unnecessary and also created unpredictable and undesirable scrolling behaviours. Most notably, if any interactions were made on the page during the time fixScroll was excessively executing, unexpected "scroll to bottom" events would be triggered.

It seems the desired functionality is already well-handled by the `adjustScrollPositionForContentChanges` function, so, I've made the decision to remove the outdated fixScroll related code.

https://github.com/zer0-os/zOS/assets/39112648/3353e492-cfa2-4636-9246-4af906411689

2023-08-25 10:15 UTC, ratik21 approved these changes
Could you please test loading messaging in channels, DM's & group DM's even when we're "recieving" new messages. Just to confirm if there's a case we didn't miss out on before removing this code.

2023-08-25 11:40 UTC, domw30 commented
> Could you please test loading messaging in channels, DM's & group DM's even when we're "recieving" new messages. Just to confirm if there's a case we didn't miss out on before removing this code.

To confirm - @ratik21 and I tested this together to ensure we're still getting the correct behaviours.

2023-08-25 12:08 UTC, domw30 commented
Thanks for the review @ratik21, I'm hesitant to merge this one today - would like to get @dalefukami's thoughts as well in case we've missed something this code was supporting.

2023-08-28 15:36 UTC, dalefukami approved these changes
My guess is that this had something to do with delayed loading of url previews/images/etc which would change the height of the scrollable content and since we're using an inverted scroll that all gets kinda dicey. It's possible this is no longer an issue because of new display techniques that weren't available when this was originally written (copied from zero-web likely). In any case, I'm good with removing it and fixing whatever issue may arise.

2023-08-28 15:53 UTC, dalefukami requested changes
Looks like this has broken some functionality:


https://github.com/zer0-os/zOS/assets/43770/b9370184-f87a-4071-9530-fcb64e808a0b

2023-08-29 09:53 UTC, domw30 commented
> Looks like this has broken some functionality:
> 
>  brokenscroll.mp4

Ah yes good spot, I'll look into this.

2023-08-29 14:25 UTC, domw30 commented
@dalefukami - I re-introduced the `fixScroll` functionality here but reduced the number set for `SCROLL_HEIGHT_FIXER_ITERATIONS` from `1000` to `200` so it is not so aggressive. Reducing the number of iterations appears to resolve the unpredictable scrolling, and continues to scroll to bottom on load.

2023-08-29 16:57 UTC, dalefukami commented
I kinda feel like we're hacking this thing without truly understanding what it's doing. Shrinking it to 200 maybe works perfectly for the exact network conditions that you tested on but what if the network is slower or there are 50 large images to download? How do you know that 200 is the right number?

2023-09-07 17:18 UTC, dalefukami commented
Closing in favor of #972

2023-09-07 17:18 UTC, closed without merging